//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devices
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public string PhoneModel { get; set; }
        public string PhoneMarka { get; set; }
        public string DeviceType { get; set; }
        public string SerialNumber { get; set; }
        public System.DateTime ManufactureDate { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
