//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int OrderKods { get; set; }
        public int PartId { get; set; }
        public int WorkId { get; set; }
        public int DeviceId { get; set; }
        public string OrderType { get; set; }
    
        public virtual DevicesDb DevicesDb { get; set; }
        public virtual PartsDb PartsDb { get; set; }
        public virtual WorksDb WorksDb { get; set; }
    }
}
