//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id { get; set; }
        public int OrderKods { get; set; }
        public int PartId { get; set; }
        public Nullable<int> WorkId { get; set; }
        public int UserId { get; set; }
        public int DeviceId { get; set; }
        public string OrderType { get; set; }
        public Nullable<int> SparePhone { get; set; }
    
        public virtual DevicesDbs DevicesDbs { get; set; }
        public virtual DevicesDbs DevicesDbs1 { get; set; }
        public virtual PartsDbs PartsDbs { get; set; }
        public virtual UsersDbs UsersDbs { get; set; }
        public virtual WorksDbs WorksDbs { get; set; }
    }
}
