//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseService
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class DoctorPhoneEntities2 : DbContext
    {
        public DoctorPhoneEntities2()
            : base("name=DoctorPhoneEntities2")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<ClientsDbs> ClientsDbs { get; set; }
        public virtual DbSet<DevicesDbs> DevicesDbs { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<PartsDbs> PartsDbs { get; set; }
        public virtual DbSet<UsersDbs> UsersDbs { get; set; }
        public virtual DbSet<WorksDbs> WorksDbs { get; set; }
    }
}
