//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sellings
    {
        public int Id { get; set; }
        public int Kod { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int Status { get; set; }
        public int UserId { get; set; }
        public int ClientId { get; set; }
        public int PartId { get; set; }
        public int Count { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Parts Parts { get; set; }
        public virtual Users Users { get; set; }
    }
}
